#!/usr/bin/env bash
# Reproducible build + sync pipeline for the TFPT document set.
# Usage:  bash build.sh           (build everything: gen + notes + archived papers)
#         bash build.sh notes     (gen + the active document set incl. changelog)
#         bash build.sh papers    (only the archived tfpt-45 papers 00-07)
#         bash build.sh gen       (only regenerate the single-source surfaces:
#                                  script index tex/tsx + content maps)
#         bash build.sh website   (sync the website mirror: PDFs, vN scripts,
#                                  version.ts, release.ts hashes + version/date)
#         bash build.sh audit     (run verification/audit_sync.py)
#         bash build.sh release   (gen -> notes -> website -> audit -> npm build;
#                                  the full pre-commit pipeline)
#         bash build.sh zenodo    (notes + upload Zenodo draft; version = TFPTversion + rev)
#         bash build.sh zenodo-publish  (same, then publish on Zenodo)
#
# Requirements: TeX Live / MacTeX (`pdflatex`), python3, node/npm (website).
# All relative \input paths resolve when each document is compiled from the
# directory shown below, so no manual file copying is needed.

set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
PASS=0; FAIL=0; FAILED=()

# --- automatic build revision: git commit count -> tex-artefacts/version-auto.tex
#     (gitignored; \input by tex-artefacts/version.tex; overrides the "dev" fallback).
REV="$(git -C "$ROOT" rev-list --count HEAD 2>/dev/null || echo 0)"
VER="$(sed -n 's/\\def\\TFPTversion{\(.*\)}/\1/p' "$ROOT/tex-artefacts/version.tex")"
mkdir -p "$ROOT/tex-artefacts"
printf '%%%% generated by build.sh -- do not edit, gitignored\n\\def\\TFPTrev{%s}\n' "$REV" \
  > "$ROOT/tex-artefacts/version-auto.tex"
printf '%s\n' "${VER} (rev ${REV})" > "$ROOT/tex-artefacts/release-version.txt"

build_one() {  # $1 = working dir, $2 = tex basename (no extension)
  local dir="$1" base="$2"
  ( cd "$dir" && pdflatex -interaction=nonstopmode -halt-on-error "$base.tex" >/dev/null 2>&1 \
                && pdflatex -interaction=nonstopmode -halt-on-error "$base.tex" >/dev/null 2>&1 )
  if ! { [ -f "$dir/$base.pdf" ] && [ "$dir/$base.tex" -ot "$dir/$base.pdf" ]; }; then
    # corrupt/stale aux files (e.g. from an interrupted run) poison the build --
    # clean the auxiliaries once and retry before declaring failure
    rm -f "$dir/$base.aux" "$dir/$base.toc" "$dir/$base.out"
    ( cd "$dir" && pdflatex -interaction=nonstopmode -halt-on-error "$base.tex" >/dev/null 2>&1 \
                  && pdflatex -interaction=nonstopmode -halt-on-error "$base.tex" >/dev/null 2>&1 )
  fi
  if [ -f "$dir/$base.pdf" ] && [ "$dir/$base.tex" -ot "$dir/$base.pdf" ]; then
    local pages=""
    command -v pdfinfo >/dev/null 2>&1 && pages=$(pdfinfo "$dir/$base.pdf" 2>/dev/null | awk '/^Pages/{print $2" pages"}')
    printf "  [OK]   %-52s %s\n" "$base" "${pages:+($pages)}"; PASS=$((PASS+1))
  else
    printf "  [FAIL] %-52s\n" "$base"; FAIL=$((FAIL+1)); FAILED+=("$base")
    # On failure, drop the .aux so a half-written/corrupt cross-reference file
    # cannot poison the next build (the .log is kept for diagnosis).
    rm -f "$dir/$base.aux" "$dir/$base.toc" "$dir/$base.out"
  fi
  # NOTE: on SUCCESS the intermediate LaTeX artefacts (.aux/.log/.out/.toc) are
  # deliberately kept -- the .log is needed for the overfull-box audit and the
  # .aux/.toc for correct cross-references on the next incremental build.
}

NOTES=(
  introduction
  tfpt_1_architecture_e8
  tfpt_2_standard_model
  tfpt_3_e8_audit_bootstrap
  tfpt_4_frontier
  tfpt_5_redteam
  tfpt_horizon_readouts
  tfpt_research_contracts
  origin_theory
  changelog
)
PAPERS=(
  00_orientation_note
  01_boundary_kernel
  02_carrier_rigidity_standard_model_packet
  03_electromagnetic_closure_flavor_transport
  04_admissibility_strong_cp_qft_closure
  05_geometric_hodge_closure_dimensionless_metrology
  06_cosmology_interfaces_downstream_closure
  07_cmb_operational_closure_planck_pipeline
)

run_gen() {  # regenerate every single-source surface (cheap, stdlib python only)
  echo "== Generated surfaces (script index + content maps + changelog mirror) =="
  python3 "$ROOT/verification/make_script_index.py" || exit 1
  python3 "$ROOT/verification/make_docs_map.py" || exit 1
  python3 "$ROOT/verification/make_changelog_web.py" || exit 1
  python3 "$ROOT/verification/make_script_atlas.py" || exit 1
}

run_website() {  # mirror PDFs + scripts into website/, stamp version + hashes
  echo "== Website mirror sync =="
  local VER DATE
  VER="$(sed -n 's/\\def\\TFPTversion{\(.*\)}/\1/p' "$ROOT/tex-artefacts/version.tex")"
  DATE="$(date +%F)"
  for b in "${NOTES[@]}"; do
    [ -f "$ROOT/$b.pdf" ] && cp "$ROOT/$b.pdf" "$ROOT/website/public/papers/"
  done
  rm -f "$ROOT"/website/public/verification/v*.py
  cp "$ROOT/verification/tfpt_constants.py" "$ROOT"/verification/v*.py \
     "$ROOT/verification/predictions_frozen.json" "$ROOT/website/public/verification/"
  cat > "$ROOT/website/lib/version.ts" <<EOF
// GENERATED by \`bash build.sh website\` -- do not edit by hand.
// Single source: tex-artefacts/version.tex (\TFPTversion) + git commit count.
export const SITE_VERSION = "$VER";
export const SITE_REV = "$REV";
export const SITE_DATE = "$DATE";
EOF
  ( cd "$ROOT/website" \
    && node scripts/release-hashes.mjs --write --version "TFPT $VER" --date "$DATE" >/dev/null )
  echo "  synced: ${#NOTES[@]} PDFs, vN scripts, version.ts (v$VER, $DATE, rev $REV), release.ts"
}

run_audit() {
  echo "== Sync audit =="
  python3 "$ROOT/verification/audit_sync.py" || exit 1
}

run_zenodo() {  # $1 = optional "publish"
  local publish_args=()
  [ "${1:-}" = "publish" ] && publish_args=(--publish)
  if [ ! -f "$ROOT/tex-artefacts/release-version.txt" ]; then
    echo "ERROR: tex-artefacts/release-version.txt missing" >&2
    exit 1
  fi
  echo "== Zenodo upload ($(cat "$ROOT/tex-artefacts/release-version.txt")) =="
  # bash 3.2 (macOS) under `set -u`: expanding an empty array errors, so guard it
  python3 "$ROOT/scripts/zenodo_upload.py" ${publish_args[@]+"${publish_args[@]}"}
}

WHAT="${1:-all}"
case "$WHAT" in
  gen)     run_gen ;;
  website) run_website ;;
  audit)   run_audit ;;
esac

if [ "$WHAT" = "zenodo" ] || [ "$WHAT" = "zenodo-publish" ]; then
  run_gen
  echo "== Active document set (compiled from repo root) =="
  for b in "${NOTES[@]}"; do build_one "$ROOT" "$b"; done
  echo "------------------------------------------------------------"
  echo "build summary: $PASS ok, $FAIL failed"
  if [ "$FAIL" -gt 0 ]; then printf '  failed: %s\n' "${FAILED[*]}"; exit 1; fi
  if [ "$WHAT" = "zenodo-publish" ]; then
    run_zenodo publish
  else
    run_zenodo
  fi
  exit 0
fi

if [ "$WHAT" = "all" ] || [ "$WHAT" = "notes" ] || [ "$WHAT" = "release" ]; then
  run_gen
  echo "== Active document set (compiled from repo root) =="
  for b in "${NOTES[@]}"; do build_one "$ROOT" "$b"; done
fi
if [ "$WHAT" = "all" ] || [ "$WHAT" = "papers" ]; then
  echo "== TFPT 4.5 papers (compiled from _archive/tfpt-45/) =="
  for b in "${PAPERS[@]}"; do build_one "$ROOT/_archive/tfpt-45" "$b"; done
fi

if [ "$WHAT" = "all" ] || [ "$WHAT" = "notes" ] || [ "$WHAT" = "papers" ] || [ "$WHAT" = "release" ]; then
  echo "------------------------------------------------------------"
  echo "build summary: $PASS ok, $FAIL failed"
  if [ "$FAIL" -gt 0 ]; then printf '  failed: %s\n' "${FAILED[*]}"; exit 1; fi
fi

if [ "$WHAT" = "release" ]; then
  run_website
  run_audit
  echo "== Website production build =="
  ( cd "$ROOT/website" && npm run build ) || exit 1
  echo "release pipeline complete -- remember: python verification/make_manifest.py LAST"
fi
