#!/usr/bin/env python3
"""Generate the central content maps (NO physical paper split needed).

Outputs (all committed, regenerated by `bash build.sh gen`):

  verification/docs_map.csv      -- paper -> section -> line range, scripts
                                    cited there, content hash, last-changed date
  verification/website_map.csv   -- mirror-surface map: website file (plus the
                                    root README.md) -> scripts +
                                    documents it mentions
  verification/docs_map_dates.json -- sidecar: per-section content hash + the
                                    date the hash last changed (committed so
                                    dates persist across machines)

Purpose: when a result changes, grep these maps for the affected script /
document to enumerate EVERY surface (paper section + website file) that has to
move in the same change.  This is the machine-readable version of the
deep-sync rule.

Date semantics: `last_changed` is the date the section's content hash last
changed as observed by this generator (backfilled from the file-level git date
on first sight).  It is a maintenance aid, not a provenance claim.

Usage:
    python3 verification/make_docs_map.py            # rewrite maps
    python3 verification/make_docs_map.py --check    # exit 1 if maps are stale

stdlib only.
"""
import csv
import datetime
import hashlib
import io
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERIF = ROOT / "verification"
WEBSITE_DIR = ROOT / "website"
DOCS_MAP = VERIF / "docs_map.csv"
WEBSITE_MAP = VERIF / "website_map.csv"
DATES_FILE = VERIF / "docs_map_dates.json"

# the active document set (changelog excluded: dated entries, no sync content)
DOCS = [
    "introduction",
    "tfpt_1_architecture_e8",
    "tfpt_2_standard_model",
    "tfpt_3_e8_audit_bootstrap",
    "tfpt_4_frontier",
    "tfpt_5_redteam",
    "tfpt_horizon_readouts",
    "tfpt_research_contracts",
    "origin_theory",
    "tfpt_safeguards",
]

SCRIPT_RX = re.compile(r"v\d+_[A-Za-z0-9_]+\.py")
# [^%\n] -- stay on one line and ignore commented-out section commands
SECTION_RX = re.compile(r"^[^%\n]*?\\(section|subsection)\*?\{", re.M)


def read_braced(text: str, start: int) -> tuple[str, int]:
    """Return (content, end_index) of the {...} group starting at text[start]=='{'."""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{" and (i == 0 or text[i - 1] != "\\"):
            depth += 1
        elif text[i] == "}" and text[i - 1] != "\\":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
    raise ValueError("unbalanced braces")


def normalise_scripts(chunk: str) -> str:
    return chunk.replace("\\allowbreak", "").replace("\\", "").replace(" ", "")


def parse_doc(doc: str) -> list[dict]:
    """Split one document into (front matter + sections) with line ranges."""
    path = ROOT / f"{doc}.tex"
    text = path.read_text()
    marks = []  # (char_pos, kind, title)
    for m in SECTION_RX.finditer(text):
        line_start = text.rfind("\n", 0, m.start()) + 1
        title, _ = read_braced(text, m.end() - 1)
        marks.append((line_start, m.group(1), " ".join(title.split())))
    bounds = [m[0] for m in marks] + [len(text)]
    rows = []
    segments = [(0, bounds[0], "front", "(front matter)")] + [
        (marks[i][0], bounds[i + 1], marks[i][1], marks[i][2]) for i in range(len(marks))
    ]
    seen_titles: dict[str, int] = {}
    for cstart, cend, kind, title in segments:
        chunk = text[cstart:cend]
        line_start = text.count("\n", 0, cstart) + 1
        line_end = text.count("\n", 0, cend) + (0 if cend == len(text) else 0)
        scripts = sorted(set(SCRIPT_RX.findall(normalise_scripts(chunk))))
        occ = seen_titles[title] = seen_titles.get(title, 0) + 1
        rows.append(
            {
                "doc": doc,
                "kind": kind,
                "title": title,
                "occurrence": occ,
                "line_start": line_start,
                "line_end": max(line_start, line_end),
                "scripts": ";".join(scripts),
                "hash": hashlib.md5(chunk.encode()).hexdigest()[:12],
            }
        )
    return rows


def git_file_date(doc: str) -> str:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", f"{doc}.tex"],
            cwd=ROOT, capture_output=True, text=True, timeout=10,
        ).stdout.strip()
        if out:
            return out
    except Exception:
        pass
    return datetime.date.today().isoformat()


def apply_dates(rows: list[dict]) -> dict:
    """Stamp last_changed per row via the committed sidecar; return new sidecar."""
    old = {}
    if DATES_FILE.exists():
        old = json.loads(DATES_FILE.read_text())
    today = datetime.date.today().isoformat()
    new = {}
    for r in rows:
        key = f"{r['doc']}::{r['kind']}::{r['title']}::{r['occurrence']}"
        prev = old.get(key)
        if prev and prev["hash"] == r["hash"]:
            date = prev["date"]
        elif prev:
            date = today
        else:
            date = git_file_date(r["doc"])
        r["last_changed"] = date
        new[key] = {"hash": r["hash"], "date": date}
    return new


def render_docs_map(rows: list[dict]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["doc", "kind", "title", "line_start", "line_end", "scripts", "hash", "last_changed"])
    for r in rows:
        w.writerow([r["doc"], r["kind"], r["title"], r["line_start"], r["line_end"],
                    r["scripts"], r["hash"], r["last_changed"]])
    return buf.getvalue()


def registered_scripts() -> dict[str, str]:
    """module id ('v91') -> full script name ('v91_spine_tetrahedron.py')."""
    text = (VERIF / "run_all.py").read_text()
    names = re.findall(r'\("(v\d+_[A-Za-z0-9_]+)"', text)
    return {n.split("_")[0]: f"{n}.py" for n in names}


def render_website_map() -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["file", "scripts", "docs"])
    by_id = registered_scripts()
    web = WEBSITE_DIR
    files = []
    for sub in ("app", "components", "lib"):
        files += sorted((web / sub).rglob("*.ts")) + sorted((web / sub).rglob("*.tsx"))
    # non-website mirror surfaces that must move with content changes too
    files += [ROOT / "README.md"]
    for f in files:
        if not f.exists():
            continue
        text = f.read_text(errors="replace")
        scripts = set(SCRIPT_RX.findall(text))
        # README.md often cites modules by bare id (`v91`) -- resolve those
        for mid in re.findall(r"\bv(\d+)\b", text):
            full = by_id.get(f"v{mid}")
            if full:
                scripts.add(full)
        docs = sorted({d for d in DOCS + ["changelog"] if d in text})
        if scripts or docs:
            w.writerow([str(f.relative_to(ROOT)), ";".join(sorted(scripts)), ";".join(docs)])
    return buf.getvalue()


def build() -> tuple[str, str, dict]:
    rows = []
    for doc in DOCS:
        rows += parse_doc(doc)
    sidecar = apply_dates(rows)
    return render_docs_map(rows), render_website_map(), sidecar


def main() -> None:
    check_only = "--check" in sys.argv
    docs_csv, web_csv, sidecar = build()
    targets = [
        (DOCS_MAP, docs_csv),
        (WEBSITE_MAP, web_csv),
        (DATES_FILE, json.dumps(sidecar, indent=1) + "\n"),
    ]
    # Shadow-export trees ship no website/ -- website_map.csv mirrors website
    # sources that are absent there, so regenerating it would destructively drop
    # every website row (and make the manifest stale).  Skip it on such a tree,
    # mirroring make_script_index.py / make_changelog_web.py, so `build.sh gen`
    # and `build.sh notes` stay non-destructive on the shadow subset.
    if not WEBSITE_DIR.exists():
        targets = [(t, content) for t, content in targets if t != WEBSITE_MAP]
        if not check_only:
            print(f"skipped (no website/ in this tree): {WEBSITE_MAP.relative_to(ROOT)}")
    stale = [t for t, content in targets if not t.exists() or t.read_text() != content]
    if check_only:
        if stale:
            for t in stale:
                print(f"STALE (re-run make_docs_map.py): {t.relative_to(ROOT)}")
            sys.exit(1)
        print("content maps up to date")
        return
    for t, content in targets:
        if t in stale:
            t.write_text(content)
            print(f"wrote {t.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
