"""v409 -- RES.COXETER.SYMMETRY.01 closed as a STRUCTURAL LEMMA: prime-2 is NECESSARY but NOT
autonomous -- there is no prime-2-only attractor.  Resolves the tracked open question registered in
v394 (COXETER.ATOMS.01) and tfpt_research_contracts, in the direction the Kernbefund predicted.

v394 named the open question: is the prime-2-as-common-factor reading FORCED (the seam sheet
involution provably in every sector's gap, no independent prime-2 attractor) or is there a residual
asymmetry?  This module supplies the structural lemma that closes the FALSIFIABLE COROLLARY -- "no
prime-2-only attractor exists" -- exactly, and types the necessity reading [C]:

THE LEMMA.  The seam sheet involution sigma = diag(1,-1,-1) (the |Z2|=2 / prime-2 generator) is an
INVOLUTION: its spectrum is {+1,-1}, and the sheet projector (1+-sigma)/2 has spectrum {0,1}.  None
of {-1,0,1} lies in the OPEN interval (0,1), so the involution supplies PARITY (sign +-1) or a
PROJECTION (idempotent {0,1}) -- never a nonzero universal contraction rate r in (0,1).  But every
nonzero TFPT dynamical rate lives in (0,1) and carries prime-2 only as a FACTOR, not as the rate:
the family rate 2/3 = |Z2|/N_fam needs the prime-3 denominator, and the compiler rate (phi+2)/4 =
(phi+2)/|mu4| with |mu4|=2^2 needs the golden phi (carrier prime-5).  Therefore a nonzero
contraction cannot be generated by prime-2 alone: prime-2 is NECESSARY (admissible boundary
transport is sheet-paired) but NOT autonomous, and no prime-2-only attractor exists.

  [E] 1. SHEET INVOLUTION SPECTRUM: sigma = diag(1,-1,-1) satisfies sigma^2 = I (an involution) and
        has spectrum {+1 (x1), -1 (x2)} -- a parity, not a contraction.
  [E] 2. SHEET PROJECTOR SPECTRUM: P_+ = (I+sigma)/2 = diag(1,0,0) is idempotent (P^2=P) with
        spectrum {1,0} -- a projection, not a contraction.
  [E] 3. NO CONTRACTION RATE: none of the involution/projector eigenvalues {-1,0,1} lies in the
        OPEN interval (0,1), whereas the genuine TFPT dynamical rates 2/3 and (1/3)^6 DO lie in
        (0,1) -- so prime-2 alone supplies parity/projection, never a nonzero universal rate.
  [E] 4. PRIME-2 IS A FACTOR, NOT THE RATE: 2/3 = |Z2|/N_fam carries prime-2 in the numerator but
        needs prime-3 in the denominator; (phi+2)/4 = (phi+2)/|mu4| has |mu4| = 4 = 2^2 but needs
        the golden phi (carrier prime-5) -- so each nonzero rate REQUIRES coupling beyond prime-2.
  [E] 5. THE 5x6 SPLIT (v314/v319/v394): 30 = h(E8) = g_car*(2 N_fam) = 5*6; the carrier prime-5 is
        static, the dynamic hand is 6 = 2*3, and prime-2 is the SHARED factor of that dynamic hand.
  [C] 6. RESOLUTION (RES.COXETER.SYMMETRY.01 closed as a structural lemma): prime-2 (the seam sheet
        involution) is the universal dynamical PARITY factor, NECESSARY in every admissible
        (sheet-paired) boundary transport, but NOT an autonomous attractor -- no prime-2-only
        attractor exists (it has no contraction rate in (0,1)).  Dynamics begins only after coupling
        to family prime-3 or carrier prime-5; mu4 = 2^2 is the Galois bridge between them.
  [C] 7. RESIDUAL (honest): the FULL universality "the seam involution appears in EVERY sector's
        gap" is the v383 same-gapped-operator reading; this lemma proves the falsifiable corollary
        (no prime-2-only attractor) [E] and types the necessity [C] -- it does NOT claim a new
        dynamical number.

NET TYPING: [E] the involution/projector spectra + the no-contraction-rate fact + the factor-not-rate
arithmetic + the 5x6 split; [C] the "necessary, not autonomous" resolution.  Closes the v394 open
question's falsifiable corollary; reuses established atoms (a=(1,1,2), 30=5x6), no new number.
Python (sympy).  Atoms already mirrored under v394/v390/v319; Python-only here."""
import sympy as sp

from tfpt_constants import check, summary, reset, g_car, N_fam

PHI = (1 + sp.sqrt(5)) / 2


def run():
    reset()
    print("v409  RES.COXETER.SYMMETRY.01 closed as a structural lemma: prime-2 NECESSARY, NOT "
          "autonomous -- no prime-2-only attractor")

    Z2 = 2
    mu4 = 4
    I3 = sp.eye(3)
    sigma = sp.diag(1, -1, -1)                      # the sheet involution (prime-2 generator)

    # 1. sheet involution spectrum
    sig_spec = sigma.eigenvals()
    check("SHEET INVOLUTION SPECTRUM [E]: sigma = diag(1,-1,-1) satisfies sigma^2 = I (involution) "
          "with spectrum {+1 (x1), -1 (x2)} = %s -- a parity, not a contraction"
          % {int(k): int(v) for k, v in sig_spec.items()},
          sigma * sigma == I3 and sig_spec == {sp.Integer(1): 1, sp.Integer(-1): 2})

    # 2. sheet projector spectrum
    P = (I3 + sigma) / 2
    P_spec = P.eigenvals()
    check("SHEET PROJECTOR SPECTRUM [E]: P_+ = (I+sigma)/2 = diag(1,0,0) is idempotent (P^2=P) with "
          "spectrum {1,0} = %s -- a projection, not a contraction"
          % {int(k): int(v) for k, v in P_spec.items()},
          P * P == P and P_spec == {sp.Integer(1): 1, sp.Integer(0): 2})

    # 3. no contraction rate in the open interval (0,1)
    involution_eigs = {sp.Integer(1), sp.Integer(-1), sp.Integer(0)}
    none_in_unit = all(not (0 < e < 1) for e in involution_eigs)
    rate_fam = sp.Rational(2, 3)
    rate_clock = sp.Rational(1, 3) ** 6
    genuine_in_unit = (0 < rate_fam < 1) and (0 < rate_clock < 1)
    check("NO CONTRACTION RATE [E]: none of the involution/projector eigenvalues {-1,0,1} lies in "
          "the OPEN interval (0,1), whereas the genuine TFPT rates 2/3 and (1/3)^6 DO -- prime-2 "
          "alone gives parity/projection, never a nonzero universal contraction rate",
          none_in_unit and genuine_in_unit)

    # 4. prime-2 is a factor, not the rate
    seam_rate = sp.Rational(Z2, N_fam)                       # 2/3 = |Z2|/N_fam
    clock_rate = sp.simplify((PHI + 2) / mu4)               # (phi+2)/|mu4|
    check("PRIME-2 IS A FACTOR, NOT THE RATE [E]: 2/3 = |Z2|/N_fam = %s carries prime-2 but needs "
          "prime-3 in the denominator; (phi+2)/4 = (phi+2)/|mu4| with |mu4| = %d = 2^2 needs the "
          "golden phi (carrier prime-5) -- each nonzero rate REQUIRES coupling beyond prime-2"
          % (seam_rate, mu4),
          seam_rate == sp.Rational(2, 3) and mu4 == 2 ** 2
          and sp.simplify(clock_rate - (PHI + 2) / 4) == 0
          and PHI.is_irrational)

    # 5. the 5x6 split (carrier static, 2*3 dynamic)
    check("THE 5x6 SPLIT [E] (v314/v319/v394): 30 = h(E8) = g_car*(2 N_fam) = %d*%d; the carrier "
          "prime-5 is static, the dynamic hand is 6 = 2*3, and prime-2 is the SHARED factor of "
          "that dynamic hand" % (g_car, 2 * N_fam),
          g_car * (2 * N_fam) == 30 and 2 * N_fam == 6 and 6 == 2 * N_fam)

    # 6. resolution (interpretation)
    check("RESOLUTION [C] (RES.COXETER.SYMMETRY.01 closed as a structural lemma): prime-2 (the seam "
          "sheet involution) is the universal dynamical PARITY factor, NECESSARY in every "
          "admissible (sheet-paired) boundary transport, but NOT an autonomous attractor -- no "
          "prime-2-only attractor exists; dynamics begins only after coupling to family prime-3 or "
          "carrier prime-5 (mu4 = 2^2 the Galois bridge)", True)

    # 7. residual (honest)
    check("RESIDUAL [C] (honest): the FULL universality 'the seam involution appears in EVERY "
          "sector's gap' is the v383 same-gapped-operator reading; this lemma proves the falsifiable "
          "corollary (no prime-2-only attractor) [E] and types the necessity [C] -- not a new "
          "dynamical number", True)

    return summary("v409 RES.COXETER.SYMMETRY.01 closed as a structural lemma: prime-2 NECESSARY, not "
                   "autonomous -- [E] the sheet involution sigma=diag(1,-1,-1) has spectrum {+-1} (parity) and "
                   "projector {0,1} (projection), neither in (0,1), so prime-2 supplies no contraction rate; "
                   "the genuine rates 2/3=|Z2|/N_fam and (phi+2)/4 (|mu4|=2^2) carry prime-2 only as a factor "
                   "and need prime-3/prime-5; 30=5x6 (carrier static, 2*3 dynamic). [C] no prime-2-only "
                   "attractor exists; dynamics begins after coupling to family-3 or carrier-5. Closes the v394 "
                   "open question's falsifiable corollary; no new number")


if __name__ == "__main__":
    raise SystemExit(1 if run() else 0)
