#!/usr/bin/env python3
"""Upload a new TFPT version to Zenodo (InvenioRDM API).

Creates a new record version of the existing deposit, uploads PDF files,
updates description from zenodo_description.html, and optionally publishes.

Environment:
  ZENODO_TOKEN   Personal access token (deposit:write + deposit:actions)
  ZENODO_RECORD  Latest published record id (default: 20681451)

Usage:
  python3 scripts/zenodo_upload.py --dry-run
  python3 scripts/zenodo_upload.py
  python3 scripts/zenodo_upload.py --publish
  bash build.sh zenodo-publish          # notes + publish (reads release-version.txt)

Never commit the token. Use a local `.env` (gitignored) or GitHub secret ZENODO_TOKEN.
Version label default: `{TFPTversion} (rev {git count})` from `tex-artefacts/release-version.txt`
(generated by any `build.sh` invocation).
API reference: https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RECORD_ID = "20681451"  # 5.1 (rev 105), published 2026-06-13; DOI 10.5281/zenodo.20681451
ZENODO_API = "https://zenodo.org/api"
REPO_URL = "https://github.com/sthamann/tfpt-theoryv4"

PDF_FILES = (
    "introduction.pdf",
    "origin_theory.pdf",
    "tfpt_1_architecture_e8.pdf",
    "tfpt_2_standard_model.pdf",
    "tfpt_3_e8_audit_bootstrap.pdf",
    "tfpt_4_frontier.pdf",
    "tfpt_5_redteam.pdf",
    "tfpt_horizon_readouts.pdf",
    "tfpt_research_contracts.pdf",
    "changelog.pdf",
)


def load_dotenv(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def api_request(
    method: str,
    path: str,
    token: str,
    *,
    data: bytes | None = None,
    headers: dict[str, str] | None = None,
    expect_json: bool = True,
) -> Any:
    url = path if path.startswith("http") else f"{ZENODO_API}{path}"
    hdrs = {"Authorization": f"Bearer {token}"}
    if headers:
        hdrs.update(headers)
    req = urllib.request.Request(url, data=data, headers=hdrs, method=method)
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            body = resp.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"{method} {url} -> HTTP {exc.code}: {detail}") from exc

    if not expect_json or not body:
        return None
    return json.loads(body.decode("utf-8"))


def read_semantic_version(default: str = "5.1") -> str:
    text = (ROOT / "tex-artefacts" / "version.tex").read_text(encoding="utf-8")
    match = re.search(r"\\def\\TFPTversion\{([^}]+)\}", text)
    return match.group(1) if match else default


def read_git_rev(default: str = "0") -> str:
    auto = ROOT / "tex-artefacts" / "version-auto.tex"
    if auto.is_file():
        match = re.search(r"\\def\\TFPTrev\{([^}]+)\}", auto.read_text(encoding="utf-8"))
        if match:
            return match.group(1)
    try:
        out = subprocess.check_output(
            ["git", "-C", str(ROOT), "rev-list", "--count", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return out or default
    except (subprocess.CalledProcessError, FileNotFoundError):
        return default


def read_release_version() -> str:
    """Full Zenodo version label: semantic version + git iteration (matches \\TFPTdatestamp)."""
    release_file = ROOT / "tex-artefacts" / "release-version.txt"
    if release_file.is_file():
        line = release_file.read_text(encoding="utf-8").strip()
        if line:
            return line
    return f"{read_semantic_version()} (rev {read_git_rev()})"


def read_description_html() -> str:
    return (ROOT / "zenodo_description.html").read_text(encoding="utf-8")


def create_new_version(token: str, record_id: str) -> str:
    draft = api_request("POST", f"/records/{record_id}/versions", token)
    draft_id = str((draft or {}).get("id", ""))
    if not draft_id.isdigit():
        raise RuntimeError(f"Unexpected new-version response: {json.dumps(draft)[:800]}")
    return draft_id


def get_draft(token: str, record_id: str) -> dict:
    draft = api_request("GET", f"/records/{record_id}/draft", token)
    assert isinstance(draft, dict)
    return draft


def list_draft_files(token: str, record_id: str) -> list[dict]:
    result = api_request("GET", f"/records/{record_id}/draft/files", token)
    if isinstance(result, dict):
        return list(result.get("entries") or result.get("files") or [])
    if isinstance(result, list):
        return result
    return []


def delete_draft_file(token: str, record_id: str, key: str) -> None:
    encoded = urllib.parse.quote(key, safe="")
    api_request(
        "DELETE",
        f"/records/{record_id}/draft/files/{encoded}",
        token,
        expect_json=False,
    )


def upload_draft_file(token: str, record_id: str, filepath: Path) -> None:
    key = filepath.name
    encoded = urllib.parse.quote(key, safe="")

    init_payload = json.dumps([{"key": key}]).encode("utf-8")
    api_request(
        "POST",
        f"/records/{record_id}/draft/files",
        token,
        data=init_payload,
        headers={"Content-Type": "application/json"},
    )

    content = filepath.read_bytes()
    api_request(
        "PUT",
        f"/records/{record_id}/draft/files/{encoded}/content",
        token,
        data=content,
        headers={
            "Content-Type": "application/octet-stream",
            "Content-Length": str(len(content)),
        },
        expect_json=False,
    )

    api_request(
        "POST",
        f"/records/{record_id}/draft/files/{encoded}/commit",
        token,
        expect_json=False,
    )


def build_zenodo_metadata(*, version: str, description_html: str) -> dict:
    """InvenioRDM draft metadata (flat GET responses are not valid for PUT)."""
    return {
        "title": (
            "Topological Fixed Point Theory: A Carrier First Derivation of the "
            "Standard Model and Fundamental Constants from Admissibility Constraints"
        ),
        "publication_date": date.today().isoformat(),
        "description": description_html,
        "version": version,
        "publisher": "Stefan Hamann",
        "access_right": "open",
        "resource_type": {"id": "publication-preprint"},
        "license": {"id": "cc-by-4.0"},
        "creators": [
            {
                "person_or_org": {
                    "type": "personal",
                    "name": "Hamann, Stefan",
                    "family_name": "Hamann",
                    "given_name": "Stefan",
                    "identifiers": [
                        {"scheme": "orcid", "identifier": "0009-0001-2596-109X"}
                    ],
                }
            }
        ],
        "contributors": [
            {
                "person_or_org": {
                    "type": "personal",
                    "name": "Alessandro, Rizzo",
                    "family_name": "Alessandro",
                    "given_name": "Rizzo",
                },
                "role": {"id": "researcher"},
            }
        ],
        "custom": {
            "code:codeRepository": REPO_URL,
            "code:programmingLanguage": [{"id": "python"}],
            "code:developmentStatus": {"id": "active"},
        },
    }


def update_draft_metadata(
    token: str,
    record_id: str,
    *,
    version: str,
    description_html: str,
) -> None:
    metadata = build_zenodo_metadata(version=version, description_html=description_html)
    payload = json.dumps({"metadata": metadata}).encode("utf-8")
    api_request(
        "PUT",
        f"/records/{record_id}/draft",
        token,
        data=payload,
        headers={"Content-Type": "application/json"},
    )


def publish_draft(token: str, record_id: str) -> dict:
    published = api_request("POST", f"/records/{record_id}/draft/actions/publish", token)
    assert isinstance(published, dict)
    return published


def validate_pdfs() -> list[Path]:
    missing = [name for name in PDF_FILES if not (ROOT / name).is_file()]
    if missing:
        raise SystemExit(f"Missing PDF(s): {', '.join(missing)} — run: bash build.sh notes")
    return [ROOT / name for name in PDF_FILES]


def main() -> int:
    parser = argparse.ArgumentParser(description="Upload TFPT release to Zenodo")
    parser.add_argument(
        "--record",
        default=os.environ.get("ZENODO_RECORD", DEFAULT_RECORD_ID),
        help=f"Latest published Zenodo record id (default: {DEFAULT_RECORD_ID})",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Override version label (default: tex-artefacts/release-version.txt from build.sh)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate files and print plan without calling Zenodo write APIs",
    )
    parser.add_argument(
        "--draft-id",
        default=None,
        help="Resume an existing draft record id (skip newversion)",
    )
    parser.add_argument(
        "--publish",
        action="store_true",
        help="Publish the new version (default: stop after draft upload)",
    )
    args = parser.parse_args()

    load_dotenv(ROOT / ".env")

    token = os.environ.get("ZENODO_TOKEN", "").strip()
    if not token and not args.dry_run:
        print("ERROR: set ZENODO_TOKEN (GitHub secret or local env).", file=sys.stderr)
        return 1

    version = args.version or read_release_version()
    pdfs = validate_pdfs()
    description = read_description_html()

    print(f"Zenodo record (latest): {args.record}")
    print(f"Version label: {version}")
    print(f"PDFs ({len(pdfs)}):")
    for path in pdfs:
        print(f"  - {path.name} ({path.stat().st_size // 1024} KB)")

    if args.dry_run:
        print("Dry run — no Zenodo API writes.")
        return 0

    print("Creating new version draft…")
    if args.draft_id:
        draft_id = args.draft_id
        print(f"Resuming draft record id: {draft_id}")
    else:
        draft_id = create_new_version(token, args.record)
        print(f"Draft record id: {draft_id}")

    print("Updating metadata (description + version + repo link)…")
    update_draft_metadata(
        token,
        draft_id,
        version=version,
        description_html=description,
    )

    existing = list_draft_files(token, draft_id)
    if existing:
        print(f"Removing {len(existing)} existing draft file(s)…")
        for entry in existing:
            key = entry.get("key") or entry.get("filename")
            if key:
                delete_draft_file(token, draft_id, str(key))
                print(f"  deleted {key}")

    print("Uploading PDFs…")
    for path in pdfs:
        print(f"  + {path.name}")
        upload_draft_file(token, draft_id, path)

    if args.publish:
        print("Publishing draft…")
        published = publish_draft(token, draft_id)
        doi = (published.get("metadata") or {}).get("doi") or published.get("doi")
        links = published.get("links") or {}
        html = links.get("self_html") or links.get("record_html")
        print(f"Published: {html or published.get('id')}")
        if doi:
            print(f"DOI: {doi}")
    else:
        print(f"Draft ready (not published): https://zenodo.org/uploads/{draft_id}")
        print("Review in Zenodo, then re-run with --publish or publish in the UI.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
